//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public int Id { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string PdfUrl { get; set; }
        public string Category { get; set; }
        public string createdBy { get; set; }
        public string Date { get; set; }
        public string Visibility { get; set; }
    }
}
