//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileModelContainer : DbContext
    {
        public FileModelContainer()
            : base("name=FileModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileData> FileDatas { get; set; }
        public virtual DbSet<NewsData> NewsDatas { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
    }
}
